apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: airflow
  name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: airflow
    spec:
      containers:
      - image: puckel/docker-airflow:latest
        name: docker-airflow
        resources: {}
status: {}
